# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
     - main

variables:
  - group: SBite-PipelineVariables

stages:
  - stage: windows_and_android_stage
    displayName: Windows and Android stage
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
    jobs:
      # - job: windows_job
      #   displayName: Windows Job
      #   steps:
      #   # - template: setup_template.yml

      #   - task: Bash@3
      #     displayName: Build Windows MAUI app
      #     inputs:
      #       targetType: 'inline'
      #       script: |
      #         dotnet restore SeasonalBite.csproj
      #         dotnet publish SeasonalBite.csproj -f net8.0-windows10.0.19041.0 -c Release --output '$(Build.ArtifactStagingDirectory)/Windows' 

      #   - task: PublishBuildArtifacts@1
      #     displayName: Publish Window app to artifacts
      #     inputs:
      #       PathtoPublish: '$(Build.ArtifactStagingDirectory)/Windows' 
      #       ArtifactName: 'Windows'
            
      - job: android_job
        displayName: Android Job
        steps:
        - template: setup_template.yml

        - task: DownloadSecureFile@1
          name: keystore_file
          displayName: Download Keystore File
          inputs:
            secureFile: 'seasonalbite.keystore'

        - task: Bash@3
          displayName: Move Keystore File to Build Directory
          inputs:
           targetType: 'inline'
           script: |
            mv "$(keystore_file.secureFilePath)" "$(Build.SourcesDirectory)/seasonalbite.keystore"

        - task: Bash@3
          displayName: Set Keystore File Permissions
          inputs:
            targetType: inline
            script: |
              chmod 600 "$(Build.SourcesDirectory)/seasonalbite.keystore"
              ls -l "$(Build.SourcesDirectory)/seasonalbite.keystore"

        - task: Bash@3
          displayName: Show Current working directory
          inputs:
            targetType: 'inline'
            script: 'ls'
                        
        - task: Bash@3
          displayName: Build Android MAUI app
          env:
            COCKROACH_CONN_STR: $(cockroachDbConnectionString)
          inputs:
            targetType: 'inline'
            script: |
                echo '{ "COCKROACH_CONN_STR": "$(cockroachDbConnectionString)" }' > "$(Build.SourcesDirectory)/secrets.json"

                dotnet restore SeasonalBite.csproj
                dotnet publish SeasonalBite.csproj -f net8.0-android -c Release \
                  --output "$(Build.ArtifactStagingDirectory)/Android" \
                  -p:AndroidKeyStore=true \
                  -p:AndroidSigningKeyStore="$(Build.SourcesDirectory)/seasonalbite.keystore" \
                  -p:AndroidSigningKeyAlias=seasonalbite \
                  -p:AndroidSigningKeyPass=$(keystore_password) \
                  -p:AndroidSigningStorePass=$(keystore_password)

        - task: PublishBuildArtifacts@1
          displayName: Publish Android app to artifacts
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Android' 
            ArtifactName: 'Android'