# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
     - main

pr:
 branches:
   include:
     - main

variables:
  - group: SBite-PipelineVariables

pool: Default
  # vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: Set Dotnet Version
  inputs:
    packageType: 'sdk'
    version: $(dotnet_version)
   
- task: Bash@3
  displayName: Install Maui Workloads
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear
      dotnet workload install android maui --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

- task: Bash@3
  displayName: Show Current working directory
  inputs:
    targetType: 'inline'
    script: 'ls'

