name: SeasonalBite CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI Android Workload
      if: runner.os == 'Linux' || runner.os == 'Windows' 
      run: dotnet workload install maui-android

    - name: Install MAUI iOS Workload
      if: runner.os == 'macOS'
      run: dotnet workload install maui-ios

        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test
