name: SeasonalBite CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install MAUI Workloads
      run: |
        dotnet workload install maui-android
        dotnet workload install maui-ios
        dotnet workload install maui-maccatalyst
    
    - name: Restore dependencies
      run: |
        dotnet restore SeasonalBite.csproj
    
    - name: Build the project
      run: |
        dotnet build SeasonalBite.csproj -f net8.0-android --configuration Release
        dotnet build SeasonalBite.csproj -f net8.0-ios --configuration Release
        dotnet build SeasonalBite.csproj -f net8.0-maccatalyst --configuration Release
    
    - name: Run tests
      run: dotnet test SeasonalBiteUnitTests/SeasonalBiteUnitTests.csproj -f net8.0
